### ISSUE TITLE
Verify input parameters for External task

### ISSUE THREAD

**Issue by KhodyrevDS** [camunda-community-hub/bpmn-driven-testing#139]
How I can verify input parameters for External task (from input/output  tab)?

**Comment by gclaussn** [comment]
hi @KhodyrevDS,

please have a look at this [commit](https://github.com/camunda-community-hub/bpmn-driven-testing/commit/3dae568729c0bb4953011319964392fa109971e0): it shows an example process with one external task that has one input parameter (`increment`) and one output parameter (`decrement`).

For the assertion of input parameters, you have to use the external task handler of the activity. If you use the #executeExternalTask callback, you have access of an already locked external task and can use its execution ID to get the variables via RuntimeService#getVariables. If you use #executeLockedExternalTask callback, the variables should be availabe via LockedExternalTask#getVariables. When you need to run some other code that locks and completes the external task as part of your test, you need to unlock it first via ExternalTaskService#unlock and then run your own code to proceed at this wait state.

For the assertion of output parameters, you have to use the `verify` callback of the next wait state or like shown in this example the `verify` callback of the test case, if there is further wait state. In those callback you need to use bpmn assert semantics or get the current execution ID and access the variables again via RuntimeService#getVariables.

Please give me a feedback, if this helps and the issue can be closed.

**Comment by KhodyrevDS** [comment]
Thank you. I found solushion like your example

tc1.handleExternalTask().verify((pi, topic) -> {
  tc1.getProcessEngine().getRuntimeService().getVariablesLocal(pi.externalTask().getActual().getExecutionId());
  ...
})

But it will be better to have something like pi.variables()...

**Comment by gclaussn** [comment]
yes that would be nice. I need to check if I can improve the #verify callback of the ExternalTaskHandler a bit.

**Comment by gclaussn** [comment]
hi @KhodyrevDS,

I added an additional verify callback that accepts an `ExternalTaskAssert` and a map, containing the task's local variables - please see:
- [Example test](https://github.com/camunda-community-hub/bpmn-driven-testing/blob/issue-139-external-task-input-output/integration-tests/advanced/src/test/java/org/example/it/ExternalTaskInputOutputTest.java#L18-L22)
- [ExternalTaskHandler#verifyTask](https://github.com/camunda-community-hub/bpmn-driven-testing/blob/issue-139-external-task-input-output/impl/src/main/java/org/camunda/community/bpmndt/api/ExternalTaskHandler.java#L229-L240)

For assertion of non local variables, it still can be combined with the existing `verify`:
```java
handler.verify((pi, topicName) -> {
  pi.variables().containsEntry("i", 10L);

  assertThat(topicName).isEqualTo("test-topic");
});

handler.verifyTask((externalTaskAssert, localVariables) -> {
  externalTaskAssert.hasTopicName("test-topic");

  assertThat(localVariables).containsEntry("increment", 11L);
});
```

Would this be helpful? If so, it can be added to the next release.

Best regards

**Comment by KhodyrevDS** [comment]
Thank you
