### ISSUE TITLE
bpmn-driven-testing with camunda-process-test-coverage

### ISSUE THREAD

**Issue by KhodyrevDS** [camunda-community-hub/bpmn-driven-testing#140]
Hello, is it possible add https://github.com/camunda-community-hub/camunda-process-test-coverage functionality to bpmn-driven-testing?

**Comment by gclaussn** [comment]
hi @KhodyrevDS, I will have a look on how this can be achieved.

**Comment by gclaussn** [comment]
hi @KhodyrevDS, I have added 3 Maven projects as examples under integration-tests/ on branch issue-140-process-test-coverage:
- [coverage-junit5](https://github.com/camunda-community-hub/bpmn-driven-testing/tree/issue-140-process-test-coverage/integration-tests/coverage-junit5) (without Spring)
- [coverage-spring-junit5](https://github.com/camunda-community-hub/bpmn-driven-testing/tree/issue-140-process-test-coverage/integration-tests/coverage-spring-junit5)
- [coverage-spring-boot-junit5](https://github.com/camunda-community-hub/bpmn-driven-testing/tree/issue-140-process-test-coverage/integration-tests/coverage-spring-boot-junit5)

If tests are executed, the coverage report is created under target/process-test-coverage as expected.

**Comment by KhodyrevDS** [comment]
Thank you, it work for me
