### ISSUE TITLE
Build fails when trying to upload SNAPSHOTS to https://oss.sonatype.org//content/repositories/snapshots

### ISSUE THREAD

**Issue by gclaussn** [camunda-community-hub/bpmn-driven-testing#185]
When merging a pull request into Master, the SNAPSHOT build fails with following error `401 Content access is protected by token`. :warning: there error occurred with the last commit, which did no changes to the build at all - beside adding one test dependency.

Here the complete Maven error:
```
Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (deploy-to-maven-central) on project bpmn-driven-testing-8-maven-plugin:
Failed to deploy artifacts: Could not transfer artifact org.camunda.community:bpmn-driven-testing-impl:jar:0.12.0-20240622.091051-2 from/to central (https://oss.sonatype.org//content/repositories/snapshots): authentication failed for https://oss.sonatype.org//content/repositories/snapshots/org/camunda/community/bpmn-driven-testing-impl/0.12.0-SNAPSHOT/bpmn-driven-testing-impl-0.12.0-20240622.091051-2.jar, status: 401 Content access is protected by token -> [Help 1]
```

Action run:
https://github.com/camunda-community-hub/bpmn-driven-testing/actions/runs/9624274107/job/26547969585

**Comment by gclaussn** [comment]
@camunda-community-hub/devrel is this a general problem or related to this repository?

**Comment by xomiamoore** [comment]
Hey @gclaussn, thanks for the tag -- looks like our infrastructure team is in the process of fixing this. Maven Central is moving to tokens and the username/password authentication we were previously using are now deprecated, and they are working on that update now. It should be complete in the next few days.

**Comment by xomiamoore** [comment]
Hey there! The [GitHub Action](https://github.com/camunda-community-hub/community-action-maven-release/tree/v1.2) is now up-to-date with the new credentials, so please try again with the new version and let me know if you run into any other problems!

**Comment by gclaussn** [comment]
see #186
