### ISSUE TITLE
Update deployment GitHub Action

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/bpmn-driven-testing#186]
Hello! We had to make a few changes to our community's Maven deployment Action. Specifically, we updated the secret names and deployment credentials.

Please update to [the latest release, v. 1.2.1](https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.2.1), to make sure your Action works. Thank you!

**Comment by gclaussn** [comment]
Hi @xomiamoore,

I updated the deploy workflow:
https://github.com/camunda-community-hub/bpmn-driven-testing/commit/9e385c84b11b42aea79e14cc00bea7d9902c738d

It seems to work now:
https://github.com/camunda-community-hub/bpmn-driven-testing/actions/runs/9718708631/job/26827330511

Do I also need to update the action's version?
`camunda-community-hub/community-action-maven-release@v1` -> `camunda-community-hub/community-action-maven-release@v1.2.1` ?

Thank you for your efforts!

**Comment by xomiamoore** [comment]
@gclaussn, it looks like it's working despite that, but I'd change it to `v.2.1` just to be safe :) Glad it's working now!! 🎉
