### ISSUE TITLE
Process with two collapsed Subprocesses creates unexpected test paths

### ISSUE THREAD

**Issue by nyuuyn** [camunda-community-hub/bpmn-driven-testing#188]
Hi lovely people,

I really love the idea of the project and wanted to use it in our project, however, right from the get go I have questions regardin the following example process:

![grafik](https://github.com/user-attachments/assets/1648767a-7852-48be-a908-539da9cfd7ab)

As you can see the path finding of the plugin goes into the collapsed Subprocess A and marks each task/event inside for the test path, as you can see here:

![grafik](https://github.com/user-attachments/assets/8ca6eff5-a9ef-4758-928d-4e547c6dd801)

However, in subprocess B it does not, see here:

![grafik](https://github.com/user-attachments/assets/a7c5f1ad-540e-40ca-812a-d3c8c01e1d48)

After a little debugging it seems the next outgoing element inside the path finding algorithm returns the Subprocess Activity and not the Start Event inside.

Is this an expected behavior ? Am I missing something?

**Comment by gclaussn** [comment]
hi @nyuuyn, I need to check this. I never tested it with collapsed subprocesses - not used this BPMN/modeler so far. but nevertheless I would also expect that the modeler extension supports this construct. maybe a fix from my side is necessary.

can you please provide me a BPMN XML as an example, so that I can reproduce the bug.

**Comment by gclaussn** [comment]
I reproduced it.

no you are doing fine. the behavior should be a different one!

very strange. in the BPMN XML the collapsed subprocess appears as `bpmn:subProcess` - the same as a embedded subprocess does. so there only difference the BPMN diagram. but the `bpmndi` elements are completed ignored by BPMN driven testing.

the path finding problem seems to occur when there are 2 consecutive subprocesses:
![image](https://github.com/user-attachments/assets/09405156-c46b-4168-983f-5d625b5d07fc)

**Comment by nyuuyn** [comment]
No worries, thanks in advance! I will have a look on this issue and PR hopefully to learn and next time maybe I can help fixing an issue as well. 

Like I wrote, the project is highly interesting to me  :)

**Comment by nyuuyn** [comment]
Dear @gclaussn,

found a possible fix have a look at PR #189 and feel free to give suggestions :)

Regards

**Comment by gclaussn** [comment]
hi, @nyuuyn,

I found only minor things. Nothing that must to be changed. I will have a look (maybe tomorrow) on the examples BPMNs and approve it afterwards.

**Comment by gclaussn** [comment]
hi @nyuuyn,

your fix is merged. :-)

it will be part of the upcoming release in August.
