### ISSUE TITLE
[Question][C7] Regarding Send Message Tasks as External Tasks 

### ISSUE THREAD

**Issue by nyuuyn** [camunda-community-hub/bpmn-driven-testing#194]
Hi lovely people,

just a short question:

If I have a "Send Task" in my C7 BPMN model that is implemented via an external task, shouldn't there be a External Task Handler generated via bpmndt? Right now, it doesn't generate as such? Do I miss something?

The attached picture is just for reference

Many thanks in advance!

![grafik](https://github.com/user-attachments/assets/7cde34ce-2a79-45b9-af90-45b7cedb0c7e)

**Comment by gclaussn** [comment]
Hi @nyuuyn,

thank you for creating the issue.

Yes, you are right. The logic for determining external tasks is not complete. Only service tasks and intermediate message throw events with type external are determined:

https://github.com/camunda-community-hub/bpmn-driven-testing/blob/master/model/src/main/java/org/camunda/community/bpmndt/model/BpmnSupport.java#L171-L184

I will add some logic for send task and business rule task.

The enhancement will be included in the next release. By then, you could model a service task with type external. There should be no difference during execution.

Best regards.

**Comment by nyuuyn** [comment]
Hi @gclaussn ,

thanks for the reply, I could look into it as well and make a PR. The link you posted is a perfect starting point!

Thank you and have a nice day

**Comment by gclaussn** [comment]
Hi @nyuuyn,

I appreciate enthusiasm, but no need - already pushed 2bc0923.

**Comment by gclaussn** [comment]
hi @nyuuyn,

the enhancement is included in version 0.13.0, which has been released today.
