### ISSUE TITLE
Support Gradle builds

### ISSUE THREAD

**Issue by gclaussn** [camunda-community-hub/bpmn-driven-testing#25]
For projects that are built using Gradle, a plugin should be implemented.

The Gradle plugin must:
- Provide the same configuration options as the Maven plugin does
- Generate the same test code as the Maven plugin does
- Be implemented in Java

Information:
https://www.baeldung.com/gradle-create-plugin

**Comment by tpeetz** [comment]
I would like to help on implementing a Gradle plugin

**Comment by gclaussn** [comment]
@tpeetz sounds good.

To implemented the Gradle plugin, the current maven-plugin project needs to be converted into a Maven multi module project:
- `bpmn-driven-testing-root`: Root POM
- `bpmn-driven-testing-generator`: Module with generator code, so the it can be reused
- `bpmn-driven-testing-maven-plugin`: Maven plugin, using the generator module
- `bpmn-driven-testing-gradle-plugin`: Gradle plugin, using the generator module; should be implemented as a standalone Gradle plugin (like described here: https://www.baeldung.com/gradle-create-plugin#standalone-plugin-project)

If you want I can prepare the Maven multi module project on a branch.

Or you just start the Gradle plugin implementation by adding the necessary dependencies to `bpmn-driven-testing-maven-plugin`, writing the plugin code and the related unit tests. Then I would integrate it later on.

**Comment by tpeetz** [comment]
I would prefer a Gradle multi-module build and use a Gradle plugin to build the Maven plugin.

**Comment by gclaussn** [comment]
I'm not sure if we should or can do that, since the current release build is based on a parent POM provided by Camunda (`community-hub-release-parent`) and on a special Maven based Github action (see [deploy.yml](https://github.com/camunda-community-hub/bpmn-driven-testing/blob/master/.github/workflows/deploy.yml#L26)).

Since we just build a simple JAR, which uses `gradle-core` and `gradle-tooling-api` as dependencies, a Maven build should be fine. It would be the minimum possible change - without reworking the release build.

**Comment by gclaussn** [comment]
Gradle plugin has been released and published:
https://search.maven.org/artifact/org.camunda.community/bpmn-driven-testing-gradle-plugin

A usage description can be found here:
https://github.com/camunda-community-hub/bpmn-driven-testing/tree/master/gradle-plugin

I tested it successfully against the existing [integration tests](https://github.com/camunda-community-hub/bpmn-driven-testing/tree/master/integration-tests) using a Gradle 7.5.1 installation. Moreover I tested it with an older version of Eclipse and the current Intellij IDEA community edition.
