### ISSUE TITLE
Problem with Java build/release

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/bpmn-driven-testing#75]
It was reported a problem with the build/release. The workflow fails after uploading the SNAPSHOT artifact:
https://github.com/camunda-community-hub/bpmn-driven-testing/runs/5487179220?check_suite_focus=true

Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy-staged (default-cli) on project bpmn-driven-testing-maven-plugin: Failed to update metadata org.camunda.community/maven-metadata.xml: null: RepositoryException: NullPointerException -> [Help 1]

"Have I missed another release/change of the community-hub-release-parent or of the camunda-community-hub/community-action-maven-release step?
The build/release worked the last time for a commit on the 15th of January."

**Comment by berndruecker** [comment]
This is also puzzling to me - the build stopped working with this commit: https://github.com/camunda-community-hub/bpmn-driven-testing/commit/0c11ab32e6af1c47475541c0bc81c203865c036d. I cannot see anything wrong. Just to double-check I updated to the latest version of community-action-maven-release, but no change.

I would like to enable more logging: https://github.com/camunda-community-hub/bpmn-driven-testing/commit/53349a8507f43e05f003af5eaa9f8e7c8b0dc1b9

@gclaussn: As it seems the action currently only builds master - would you be OK to do this experiment on master or should we check to enable the action on the branch first?

**Comment by berndruecker** [comment]
@lwille just recognized that this repo is not onboarded properly and the credentials are missing.

**Comment by lwille** [comment]
meh - or so I thought! It seems the credentials are there, but it's just not working properly.

**Comment by lwille** [comment]
This last point leads me to assume that somehow the metadata in Central is broken. If you don't mind, I'm going to delete the last SNAPSHOT from January, hoping that we're going to be able to pulbish it again.

**Comment by berndruecker** [comment]
Yes - please go ahead and thanks in advance!

**Comment by gclaussn** [comment]
Thanks for the support! Just give me sign, if I should try another SNAPSHOT build.

**Comment by berndruecker** [comment]
Maybe we suffer from https://issues.apache.org/jira/browse/MNG-7375

**Comment by berndruecker** [comment]
Deleting the SNAPSHOT did not change anything

**Comment by berndruecker** [comment]
Found the defect file: https://camunda.jfrog.io/ui/repos/tree/GeneralXml/camunda-bpm-community-extensions-snapshots/org/camunda/community/maven-metadata.xml - I wonder how this corrupt file ended up there.

@lwille Can we fix or delete this file?

**Comment by lwille** [comment]
Here's the ticket: https://issues.sonatype.org/browse/OSSRH-78946

**Comment by lwille** [comment]
I'm removing my assignment here as I can't be of much help beyond opening a ticket at sonatype. I can't answer any questions they might have about this project or Maven in general.

**Comment by lwille** [comment]
If you're still interested in resolving this, please work directly with the people at [Sonatype](https://issues.sonatype.org/browse/OSSRH-78946).

**Comment by gclaussn** [comment]
I will try. Thank you, @lwille!

**Comment by berndruecker** [comment]
I updated https://issues.sonatype.org/browse/OSSRH-78946 and wait for the manual deletion of the corrupt file.

**Comment by berndruecker** [comment]
Finally sorted out, deleting the corrupt file did help: https://github.com/camunda-community-hub/bpmn-driven-testing/runs/5812929127?check_suite_focus=true. Thanks for your patience @gclaussn - should work now as expected. Let me know if you need more help

**Comment by berndruecker** [comment]
Hang on - it re-creates the file still being corrupt - so the build afterwards fails again :-(

**Comment by berndruecker** [comment]
As the new file is corrupt again it seems to be a bug in the "maven-plugin-plugin" (the problem started when this was updated from 3.5.0 to 3.6.2).

I asked Sonatype to delete the file once again and then we can try with the latest version of that pluign: https://github.com/camunda-community-hub/bpmn-driven-testing/commit/87be8188c11a4bfb0ff7ac30a517d11baaf3f79d

If this does not help we might go back top 3.5.0

**Comment by gclaussn** [comment]
Like you suggested, I reverted back to maven-plugin-plugin version 3.5 and successfully tested several subsequent SNAPSHOT builds on a branch (which I whitelisted in `deploy.yml`).

This one was really hard to find, since the commit itself, which updated the maven-plugin-plugin version, was still succesfully built... I would not have found the issue by myself!

@berndruecker thank you for efforts! please comment [OSSRH-78946](https://issues.sonatype.org/browse/OSSRH-78946), so that the ticket gets resolved and closed.
